**Task 2:** Apply algorithm on wine dataset - LabelEncoding of features: and Train test Division 66%-34%.

In [ ]:
#Import necessary libraries
import numpy as np 
import pandas as pd
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB

In [ ]:
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB
from sklearn.datasets import load_wine

wine_data = load_wine()
print('Features : \n', wine_data.feature_names)
print('\nLabels : \n', wine_data.target_names)
print("\n",wine_data.data.shape)
print(wine_data.target.shape)

Features : 
 ['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']

Labels : 
 ['class_0' 'class_1' 'class_2']

 (178, 13)
(178,)


In [ ]:
from sklearn.model_selection import train_test_split

data_train, data_test, target_train, target_test = train_test_split(wine_data.data, wine_data.target, test_size = 0.34, random_state = 115)

In [ ]:
import numpy as np
gnb = GaussianNB()

#train the model using training sets
gnb.fit(data_train, target_train)  
#predict the response of test dataset 
target_prediction = gnb.predict(data_test)  

In [ ]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

print('Accuracy : ', metrics.accuracy_score(target_test, target_prediction))
print('\nConfusion Matrix: \n',confusion_matrix(target_test, target_prediction))

precision = precision_score(target_test, target_prediction, average = None)
recall = recall_score(target_test, target_prediction, average = None)

print('\nPrecision: ',precision)
print('\nRecall: ',recall)

Accuracy :  0.9672131147540983

Confusion Matrix: 
 [[22  1  0]
 [ 0 21  1]
 [ 0  0 16]]

Precision:  [1.         0.95454545 0.94117647]

Recall:  [0.95652174 0.95454545 1.        ]
